#!/usr/bin/env bash

set -x

export MDS_URL='http://metadata.google.internal/computeMetadata/v1'
export MDS_CURL="curl -s -H Metadata-Flavor:Google ${MDS_URL}"

PROJECT_ID=$(${MDS_CURL}/project/project-id)
INSTANCE_ID=$(${MDS_CURL}/instance/id)
_GCP_REGION=$(${MDS_CURL}/instance/region)
GCP_REGION=${_GCP_REGION##*/}

PCAP_EXT="${PCAP_FILE_EXT:-pcap}"
PCAP_GZIP="${PCAP_COMPRESS:-true}" # compressing is strongly recommended
PCAP_DATE="$(date +'%Y/%m/%d/%H%M' | tr -d '\n')"
PCAP_MNT="${GCS_MOUNT:-/pcap}"
PCAP_TMP="${GCS_MOUNT:-/pcap}-tmp"
PCAP_FILE="${PCAP_TMP}/part"

# short-rotate-secs == small-pcap-files
# If APP is data intensive: keep this value small to avoid memory saturation
PCAP_SECS=${PCAP_ROTATE_SECS:-60}

# Create both paths to store PCAP files
mkdir -p ${PCAP_MNT}
mkdir -p ${PCAP_TMP}

# Start GCSFuse to mount a bucket into `GCS_MOUNT`
gcsfuse --app-name=tcpdump \
  --dir-mode=777 --file-mode=777 \
  --log-format=text -o rw ${GCS_BUCKET} ${PCAP_MNT}

# PCAP files will be indexed by Cloud RUN service, region, revision, deployment-date and instance-id
PCAP_DIR="${PCAP_MNT}/${PROJECT_ID}/${K_SERVICE}/${GCP_REGION}/${K_REVISION}/${PCAP_DATE}/${INSTANCE_ID}"
mkdir -p ${PCAP_DIR}

# listen for new PCAP files at `PCAP_TMP` and move them to GCS Bucket mounted on `PCAP_MNT`
/pcap_fsn -src=${PCAP_TMP} -dst=${PCAP_DIR} -ext=${PCAP_EXT} -gzip=${PCAP_GZIP} &

sleep 3 # wait for PCAP FS exporter to initialize

chmod -R 777 ${PCAP_TMP} # this is required because of a bug in TCPDUMP files rotation
TCPDUMP_FLAGS="${PCAP_FLAGS:--n -s 0}"
tcpdump -i any ${TCPDUMP_FLAGS} -w "${PCAP_FILE}_%Y%m%d_%H%M%S.${PCAP_EXT}" -Z root -G ${PCAP_SECS} "${PCAP_FILTER}"
