#!/usr/bin/env bash

set +x

while : ; do
    gcsfuse_ready=$(mount | grep --color=never "${PCAP_MNT} type fuse" | wc -l | tr -d '\n')
    [[ "${gcsfuse_ready}" == '1' ]] \
        && echo "{\"severity\":\"INFO\",\"message\":\"GCS Bucket ${PCAP_GCS_BUCKET} is now mounted at ${PCAP_MNT}\",\"sidecar\":\"${APP_SIDECAR}\",\"module\":\"${PROC_NAME}\"}" \
        && break
    echo "{\"severity\":\"WARNING\",\"message\":\"Waiting for GCS Bucket ${PCAP_GCS_BUCKET} to be mounted at ${PCAP_MNT} ...\",\"sidecar\":\"${APP_SIDECAR}\",\"module\":\"${PROC_NAME}\"}"
    sleep 1
done

mount | grep --color=never "${PCAP_MNT} type fuse"

set -x

mkdir -pv "${PCAP_DIR}"
