#!/usr/bin/env bash

set -xm

export ENV_FILE='/tcpdump.env'

export MDS_URL='http://metadata.google.internal/computeMetadata/v1'
export MDS_CURL="curl -s -H Metadata-Flavor:Google ${MDS_URL}"

PROJECT_ID=$(${MDS_CURL}/project/project-id)
INSTANCE_ID=$(${MDS_CURL}/instance/id)
_GCP_REGION=$(${MDS_CURL}/instance/region)
GCP_REGION=${_GCP_REGION##*/}

PCAP_EXT="${PCAP_FILE_EXT:-pcap}"
PCAP_GZIP="${PCAP_COMPRESS:-true}" # compressing is strongly recommended
PCAP_DATE="$(date +'%Y/%m/%d/%H-%M' | tr -d '\n')"
PCAP_MNT="${GCS_MOUNT:-/pcap}"
PCAP_TMP="${GCS_MOUNT:-/pcap}-tmp"
PCAP_FILE="${PCAP_TMP}/part"
GCS_DIR="${PROJECT_ID}/${K_SERVICE}/${GCP_REGION}/${K_REVISION}/${PCAP_DATE}/${INSTANCE_ID}"
PCAP_DIR="${PCAP_MNT}/${GCS_DIR}"

# short-rotate-secs == small-pcap-files
# If APP is data intensive: keep this value small to avoid memory saturation
PCAP_SECS=${PCAP_ROTATE_SECS:-60}
PCAP_SNAPLEN=${PCAP_SNAPSHOT_LENGTH:-0}

echo "PROJECT_ID=${PROJECT_ID}" >> ${ENV_FILE}
echo "GCP_REGION=${GCP_REGION}" >> ${ENV_FILE}
echo "RUN_SERVICE=${K_SERVICE}" >> ${ENV_FILE}
echo "RUN_REVISION=${K_REVISION}" >> ${ENV_FILE}
echo "INSTANCE_ID=${INSTANCE_ID}" >> ${ENV_FILE}
echo 'RUN_SIDECAR=tcpdump' >> ${ENV_FILE}
echo "GCS_DIR=${GCS_DIR}" >> ${ENV_FILE}
echo "PCAP_EXT=${PCAP_EXT}" >> ${ENV_FILE}
echo "PCAP_GZIP=${PCAP_GZIP}" >> ${ENV_FILE}
echo "PCAP_DATE=${PCAP_DATE}" >> ${ENV_FILE}
echo "PCAP_MNT=${PCAP_MNT}" >> ${ENV_FILE}
echo "PCAP_TMP=${PCAP_TMP}" >> ${ENV_FILE}
echo "PCAP_FILE=${PCAP_FILE}" >> ${ENV_FILE}
echo "PCAP_DIR=${PCAP_DIR}" >> ${ENV_FILE}

echo "GCS_BUCKET=${GCS_BUCKET}" >> ${GCS_BUCKET}
echo "PCAP_FILTER=${PCAP_FILTER}" >> ${ENV_FILE}
echo "PCAP_SECS=${PCAP_SECS}" >> ${ENV_FILE}
echo "PCAP_SNAPLEN=${PCAP_SNAPLEN}" >> ${ENV_FILE}
echo "PCAP_USE_CRON=${PCAP_USE_CRON:-false}" >> ${ENV_FILE}
echo "PCAP_CRON_EXP=${PCAP_CRON_EXP:--}" >> ${ENV_FILE}
echo "PCAP_TZ=${PCAP_TIMEZONE:-UTC}" >> ${ENV_FILE}
echo "PCAP_TO=${PCAP_TIMEOUT_SECS:-0}" >> ${ENV_FILE}

# Create both paths to store PCAP files
mkdir -p ${PCAP_MNT}
mkdir -p ${PCAP_TMP}

echo "[INFO] - PCAP files available at: gs://${GCS_BUCKET}/${GCS_DIR}"

/bin/supervisord --configuration=/tcpdump.conf --env-file=${ENV_FILE}
