#!/usr/bin/env bash

while : ; do
    [[ -d ${PCAP_DIR} ]] && break
    echo "[INFO] – PCAP files dir \'${PCAP_DIR}\' is not available"
    sleep 1
done

set -x

exec env /bin/pcap_fsn -src_dir=${PCAP_TMP} -gcs_dir=${PCAP_DIR} -pcap_ext=${PCAP_EXT} -gzip=${PCAP_GZIP}
