#!/usr/bin/env bash

while : ; do
    pcapfsn_ready=$(ps -efa | grep '/pcap_fsn' | grep -v grep | wc -l  | tr -d '\n')
    [[ "${pcapfsn_ready}" == '1' ]] && break
    echo "{\"severity\":\"WARNING\",\"message\":\"PCAP FS notifier is not running\",\"sidecar\":\"${RUN_SIDECAR}\",\"module\":\"${PROC_NAME}\"}"
    sleep 1
done

set -x

exec env /bin/tcpdumpw \
    -use_cron=${PCAP_USE_CRON:-false} \
    -cron_exp="${PCAP_CRON_EXP:--}" \
    -timezone="${PCAP_TZ:-UTC}" \
    -timeout=${PCAP_TO:-0} \
    -extension=${PCAP_EXT:-pcap} \
    -directory=${PCAP_TMP:-/pcap-tmp} \
    -snaplen=${PCAP_SNAPLEN:-0} \
    -filter="${PCAP_FILTER}" \
    -rotate_s=${PCAP_SECS}
