#!/usr/bin/env bash

set -xm

# delay GCS FUSE termination by 10s to allow remaining PCAP files to be flushed
trap 'sleep 8; kill -TERM $GCS_FUSE_PID' TERM INT
/usr/bin/gcsfuse -o rw \
  --app-name=tcpdump \
  --dir-mode=777 --file-mode=777 \
  --log-file=/dev/stdout \
  --log-format=text \
  --foreground \
  ${PCAP_GCS_BUCKET} ${PCAP_MNT} &
export GCS_FUSE_PID=$!

echo "[INFO] – GCS FUSE started w/PID: ${GCS_FUSE_PID}"
wait ${GCS_FUSE_PID}
trap - TERM INT
wait ${GCS_FUSE_PID}
echo "[INFO] – GCS FUSE ( PID: ${GCS_FUSE_PID} ) exited"
