// Code generated by "stringer -type=PcapTranslatorFmt"; DO NOT EDIT.

package transformer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TEXT-0]
	_ = x[JSON-1]
}

const _PcapTranslatorFmt_name = "TEXTJSON"

var _PcapTranslatorFmt_index = [...]uint8{0, 4, 8}

func (i PcapTranslatorFmt) String() string {
	if i < 0 || i >= PcapTranslatorFmt(len(_PcapTranslatorFmt_index)-1) {
		return "PcapTranslatorFmt(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PcapTranslatorFmt_name[_PcapTranslatorFmt_index[i]:_PcapTranslatorFmt_index[i+1]]
}
